version: 0.2
phases:
  build:
    commands:
      - docker build -t wild-rydes .
      - docker tag wild-rydes:latest $IMAGE_REPO_URL:latest
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $IMAGE_REPO_URL
      - docker push $IMAGE_REPO_URL:latest
